language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    - php: 7.3
    - php: 7.3
      env: setup=lowest
    - php: 7.4
    - php: 7.4
      env: setup=lowest
    - php: 8.0
    - php: 8.0
      env: setup=lowest
    - php: 8.1
    - php: 8.1
      env: setup=lowest
    - php: nightly
    - php: nightly
      env: setup=lowest
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

# Check for PHP syntax errors using PHP's -l flag
before_script:
  - '! find . -type f \( -path inc/vendor \) -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'

script:
  - inc/vendor/bin/phpunit
  - inc/vendor/bin/phpcs
  - composer validate --strict

test:
  script:
  - inc/vendor/bin/phpstan analyse -l max -c phpstan.neon --no-interaction --no-progress | tee phpstan_log
  artifacts:
    when: always
    expire_in: 1 month
    paths:
    - phpstan_log
